### ISSUE TITLE
似乎有些问题

### ISSUE THREAD

**Issue by augusto-lemius** [axzml/CSDNExporter#3]
```
Export Markdown File To markdown/数据结构：图(Graph)【详解】.md
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    download_csdn_single_page(args.article_url,
  File "main.py", line 138, in download_csdn_single_page
    html2md(details_url, md_file, with_title=with_title)
  File "main.py", line 56, in html2md
    parser = Parser(html)
  File "/home/soban/CSDNExporter/utils.py", line 27, in __init__
    self.recursive(self.soup)
  File "/home/soban/CSDNExporter/utils.py", line 119, in recursive
    self.recursive(child)
  File "/home/soban/CSDNExporter/utils.py", line 119, in recursive
    self.recursive(child)
  File "/home/soban/CSDNExporter/utils.py", line 119, in recursive
    self.recursive(child)
  File "/home/soban/CSDNExporter/utils.py", line 67, in recursive
    soup.contents.insert(0, NavigableString('\n```{}\n'.format(language)))
UnboundLocalError: local variable 'language' referenced before assignment
```

**Comment by axzml** [comment]
直接把 67 行 `soup.contents.insert(0, NavigableString('\n```{}\n'.format(language)))` 中的 `language` 改成空字符串, 比如`soup.contents.insert(0, NavigableString('\n```{}\n'.format('')))` , 可以暂时绕开该问题, 看来代码还有些小 bug
